In [1]:
import numpy as np
u = np.array([2, 4, 5, 6])
v= np.array([1, 0, 0, 2])

In [2]:
u + v

array([3, 4, 5, 8])

In [3]:
v.shape[0]

4

In [4]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n= u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[1] * v[i]

    return result    

In [5]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]    
])

In [6]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [7]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return  result     

In [8]:
V=np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [9]:
V


array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [10]:
vector_vector_multiplication(u, v)

np.float64(12.0)

In [11]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols =V.shape[1]

    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result    

In [12]:
matrix_matrix_multiplication(U, V)

array([[12. , 18. , 16. ],
       [ 6. ,  9. ,  8. ],
       [ 3. ,  4.5,  4. ]])

In [51]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])