In [1]:
import numpy as np


In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(10, 2.5)


array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a=np.array([1, 2, 3, 5, 7, 12])

In [11]:
a

array([ 1,  2,  3,  5,  7, 12])

In [13]:
a[2] =10

a[2]

In [14]:
a

array([ 1,  2, 10,  5,  7, 12])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [23]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
n=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]

])

In [29]:
n[1, 2] = 34

In [30]:
n

array([[ 1,  2,  3],
       [ 4,  5, 34],
       [ 7,  8,  9]])

In [33]:
n[:,2]

array([ 3, 34,  9])

In [34]:
n[:, 1]= [12, 34, 65]

In [35]:
n[:]

array([[ 1, 12,  3],
       [ 4, 34, 34],
       [ 7, 65,  9]])

In [38]:
np.random.seed(2)

100 * np.random.rand(5, 2)


array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [41]:
np.random.seed(2)

np.random.randint(low=10, high=100, size = (5, 2))

array([[50, 25],
       [82, 32],
       [53, 92],
       [85, 17],
       [44, 59]])

In [42]:
a = np.arange(5)

In [43]:
a

array([0, 1, 2, 3, 4])

In [44]:
a+1

array([1, 2, 3, 4, 5])

In [45]:
a*2

array([0, 2, 4, 6, 8])

In [48]:
b=(10 + (a *2))**2 /100

In [49]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [50]:
a + b


array([1.  , 2.44, 3.96, 5.56, 7.24])

a >= 2

In [51]:
a >= 2

array([False, False,  True,  True,  True])

In [52]:
a< b

array([ True,  True, False, False, False])

In [53]:
a

array([0, 1, 2, 3, 4])

In [54]:
a.std()

np.float64(1.4142135623730951)

In [55]:
n.sum()


np.int64(169)

In [56]:
n.min()


np.int64(1)

In [57]:
n.mean()


np.float64(18.77777777777778)